# Generated by Django 4.2.16 on 2024-09-25 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weddings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='layout1weddingdetails',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='wedding_hero_images/'),
        ),
    ]
