# Generated by Django 4.2.16 on 2024-09-26 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weddings', '0003_remove_guestphoto_message_guestphoto_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weddingsite',
            name='access_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
